[build-system]
requires = ["setuptools >= 77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jira2py"
version = "0.3.1"
description = "The Python library to interact with Atlassian Jira REST API"
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "nEver1", email = "7fhhwpuuo@mozmail.com"}
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
keywords = ["jira", "atlassian", "api", "rest", "issue-tracking"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 4 - Beta",
]
dependencies = [
    "email-validator==2.2.0",
    "pydantic==2.11.4",
    "pydantic-core==2.33.2",
    "python-dotenv==1.1.0",
    "requests==2.32.3",
]

[project.urls]
Homepage = "https://github.com/en-ver/jira2py"
Repository = "https://github.com/en-ver/jira2py"
Documentation = "https://jira2py.org/"
Issues = "https://github.com/en-ver/jira2py/issues"

[project.optional-dependencies]
deployment = [
    "setuptools>=77.0.3",
    "wheel",
    "twine",
    "build",
]
dev = [
    "ipykernel",
    "email-validator",
    "pydantic",
    "pydantic-core",
    "python-dotenv",
    "requests",
    "pytest>=8.0.0",
    "pytest-cov",  
]

[tool.setuptools]
packages = ["jira2py"]
package-dir = {"" = "src"}
