[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jira2py"
version = "0.3.0"
description = "The Python library to interact with Atlassian Jira REST API"
readme = "README.md"
authors = [
    {name = "nEver1", email = "7fhhwpuuo@mozmail.com"}
]
license = {text = "MIT"}
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "email_validator==2.2.0",
    "pydantic==2.10.4",
    "pydantic_core==2.27.2",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
]

[project.urls]
Homepage = "https://github.com/en-ver/jira2py"
Repository = "https://github.com/en-ver/jira2py"

[project.optional-dependencies]
dev = [
    "setuptools",
    "wheel",
    "twine",
]

[tool.setuptools]
packages = ["jira2py"]
